export const baseKeysMap = [
  { text: 'AC', alias: 'del', value: null },
  { text: '(', alias: 'lb', value: null },
  { text: ')', alias: 'rb', value: null },
  { text: '/', alias: 'div', value: null },
  { text: '7', alias: 'seven', value: 7 },
  { text: '8', alias: 'eight', value: 8 },
  { text: '9', alias: 'nine', value: 9 },
  { text: '*', alias: 'mul', value: null },
  { text: '4', alias: 'four', value: 4 },
  { text: '5', alias: 'five', value: 5 },
  { text: '6', alias: 'six', value: 6 },
  { text: '-', alias: 'sub', value: null },
  { text: '1', alias: 'one', value: 1 },
  { text: '2', alias: 'two', value: 2 },
  { text: '3', alias: 'three', value: 3 },
  { text: '+', alias: 'add', value: null },
  { text: '.', alias: 'point', value: null },
  { text: '0', alias: 'zero', value: 0 },
  { text: '%', alias: 'mod', value: null },
  { text: '=', alias: 'equal', value: null },
];
